# ### Field Endpoints

# # Create a new field
# POST http://localhost:3000/api/fields
# Content-Type: application/json

# {
#   "name": "Field1",
#   "location": "Location1",
#   "crop": "{{cropId}}",
#   "irrigationType": ["{{irrigationId}}"]
# }

# # Get all fields
# GET http://localhost:3000/api/fields

# # Get a single field by ID
# GET http://localhost:3000/api/fields/{{fieldId}}

# # Update a field
# PUT http://localhost:3000/api/fields/{{fieldId}}
# Content-Type: application/json

# {
#   "name": "Updated Field1",
#   "location": "Updated Location1"
# }

# # Delete a field
# DELETE http://localhost:3000/api/fields/{{fieldId}}
