# ### Irrigation Endpoints

# # Create a new irrigation system
# POST http://localhost:3000/api/irrigations
# Content-Type: application/json

# {
#   "type": "Pivot",
#   "isAutomatable": true,
#   "hoursPerInch": 2
# }

# # Get all irrigation systems
# GET http://localhost:3000/api/irrigations

# # Get a single irrigation system by ID
# GET http://localhost:3000/api/irrigations/{{irrigationId}}

# # Update an irrigation system
# PUT http://localhost:3000/api/irrigations/{{irrigationId}}
# Content-Type: application/json

# {
#   "type": "Updated Pivot",
#   "hoursPerInch": 2.5
# }

# # Delete an irrigation system
# DELETE http://localhost:3000/api/irrigations/{{irrigationId}}
